app = "carebridge-langgraph"
primary_region = "iad"  # Change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8000"

[mounts]
  source = "carebridge_data"
  destination = "/app/data" 